language: go
sudo: true #for docker service to be enabled
os: linux


install:
  - go get github.com/karalabe/xgo

script: xgo -x -v --image=mysteriumnetwork/xgo-1.9.2 --targets=linux/amd64,darwin/amd64,windows/amd64,ios-10.3/arm64 --out=test $PWD/cmd